/**
supported functions sended via mp functions (bis_fnc_mp,life_fnc_mp,...).
only packets in supported_packets will be filtered.
**/

class MP {
  supported_packets[] = {
  "life_fnc_mp_packet",
  "bis_fnc_MP_packet"
  };
  class global { //executed commands on all
    allowed_tags[] = {  // functions with other tags will be refused automaticaly
        "life",
        "bis",
        "ton"
    };

    functions[] = {
        "bis_fnc_effectkilledsecondaries",
        "bis_fnc_effectkilledairdestruction",
        "bis_fnc_setidentity",

        "life_fnc_tazesound",
        "life_fnc_flashbang",
        "life_fnc_pb_response",
        "life_fnc_ryn_message",
        "life_fnc_animsync",
        "life_fnc_playsound",
        "life_fnc_copsiren",
        "life_fnc_depsiren",
        "life_fnc_medicsiren",
        "life_fnc_coplights",
        "life_fnc_deplights",
        "life_fnc_mediclights",
        "life_fnc_pulloutveh",
        "life_fnc_lighthouse",
        "life_fnc_knockedout",
        "life_fnc_robperson",
        "life_fnc_rapesound",
        "life_fnc_rapeperson",
        "life_fnc_copmedicrequest",
        "life_fnc_sounddevice",
        "life_fnc_impoundmenu",
        "life_fnc_colorvehicle",
        "life_fnc_broadcast",
        "life_fnc_jumpfnc",
        "life_fnc_simdisable",
        "life_fnc_admininfo",
        "life_fnc_addvehicle2chain",
        "life_fnc_lockvehicle",
        "life_fnc_medicrequest",
        "life_fnc_jail",
        "life_fnc_spikestripeffect",

        "ton_fnc_clientmessage",
        "ton_fnc_cell_adminmsgall",
        "ton_fnc_cell_textmsg",
        "ton_fnc_cell_adminmsg",
        "ton_fnc_cell_adminmsgall"
    };
  };

  class client {
    allowed_tags[] = {  // functions with other tags will be refused automaticaly
        "life",
        "ac",
        "sock",
        "ton",
        "bis"
    };

    functions[] = { // Les fonctions qui n'ont pas un tag whitelisté ne seront pas acceptée même si elles se trouvent dans cette liste
    "ac_fnc_receiveadmin",
    "ac_fnc_receivenotif",

    "bis_fnc_objectvar",
    "bis_fnc_dynamictext",
    "bis_fnc_effectkilledsecondaries",
    "bis_fnc_effectkilledairdestruction",

    "life_fnc_tazesound",
    "life_fnc_revived",
    "life_fnc_jailme",
    "life_fnc_ganginvite",
    "life_fnc_seizeplayerweaponaction",
    "life_fnc_bountyreceive",
    "life_fnc_copsearch",
    "life_fnc_robreceive",
    "life_fnc_animsync",
    "life_fnc_copsiren",
    "life_fnc_pulloutveh",
    "life_fnc_civpulloutveh",
    "life_fnc_ticketprompt",
    "life_fnc_ticketpaid",
    "life_fnc_restrain",
    "life_fnc_netsetvar",
    "life_fnc_garagerefund",
    "life_fnc_givediff",
    "life_fnc_adminid",
    "life_fnc_spikestripeffect",
    "life_fnc_vehicleanimate",
    "life_fnc_depsiren",
    "life_fnc_licensecheck",
    "life_fnc_knockedout",
    "life_fnc_medicsiren",
    "life_fnc_receiveitem",
    "life_fnc_robperson",
    "life_fnc_rapesound",
    "life_fnc_rapeperson",
    "life_fnc_receivemoney",
    "life_fnc_hasorgan",
    "life_fnc_wantedremove",
    "life_fnc_sounddevice",
    "life_fnc_removelicenses",
    "life_fnc_flashbang",
    "life_fnc_impoundmenu",
    "life_fnc_colorvehicle",
    "life_fnc_broadcast",
    "life_fnc_jumpfnc",
    "life_fnc_simdisable",
    "life_fnc_licensesread",
    "life_fnc_searchclient",
    "life_fnc_admininfo",
    "life_fnc_wantedlist",
    "life_fnc_addvehicle2chain",
    "life_fnc_lockvehicle",
    "life_fnc_movein",
    "life_fnc_copmedicrequest",
    "life_fnc_wantedadd",
    "life_fnc_wantedfetch",
    "life_fnc_wantedpardon",
    "life_fnc_medicrequest",
    "life_fnc_jail",

    "sock_fnc_requestreceived",
    "sock_fnc_dataquery",
    "sock_fnc_insertplayerinfo",
    "sock_fnc_syncdata",
    "sock_fnc_updatepartial",
    "sock_fnc_updaterequest",

    "ton_fnc_clientgangleader",
    "ton_fnc_managesc",
    "ton_fnc_cell_textmsg",
    "ton_fnc_cell_adminmsg",
    "ton_fnc_clientwiretransfer",
    "ton_fnc_clientmessage",
    "ton_fnc_player_query",
    "ton_fnc_clientgetkey",
    "ton_fnc_cell_adminmsgall"
    };
};
  class server {
    allowed_tags[] = {  // functions with other tags will be refused automaticaly
    "life",
    "db",
    "ton",
    "ac",
    "bis"
    };

    functions[] = { // Les fonctions qui n'ont pas un tag whitelisté ne seront pas acceptée même si elles se trouvent dans cette liste
    "ac_fnc_log",
    "ac_fnc_adminrequest",
    "ac_fnc_logscript",

    "bis_fnc_effectkilledairdestruction",
    "bis_fnc_objectvar",
    "bis_fnc_setidentity",
    "bis_fnc_effectkilledsecondaries",
    "bis_fnc_dynamictext",

    "db_fnc_queryrequest",
    "db_fnc_insertrequest",
    "db_fnc_updaterequest",
    "db_fnc_updatepartial",
    
    "life_fnc_admininfo",
    "life_fnc_jailsys",
    "life_fnc_tazesound",
    "life_fnc_animsync",
    "life_fnc_rapesound",
    "life_fnc_wantedbounty",
    "life_fnc_knockedout",
    "life_fnc_copsiren",
    "life_fnc_receiveitem",
    "life_fnc_pulloutveh",
    "life_fnc_receivemoney",
    "life_fnc_depsiren",
    "life_fnc_medicsiren",
    "life_fnc_flashbang",
    "life_fnc_sounddevice",
    "life_fnc_wantedremove",
    "life_fnc_impoundmenu",
    "life_fnc_colorvehicle",
    "life_fnc_broadcast",
    "life_fnc_jumpfnc",
    "life_fnc_simdisable",
    "life_fnc_addvehicle2chain",
    "life_fnc_lockvehicle",
    "life_fnc_copmedicrequest",
    "life_fnc_wantedadd",
    "life_fnc_wantedfetch",
    "life_fnc_wantedpardon",
    "life_fnc_medicrequest",
    "life_fnc_jail",

    "ton_fnc_getid",
    "ton_fnc_paintball",
    "ton_fnc_game",
    "ton_fnc_managesc",
    "ton_fnc_updategang",
    "ton_fnc_clientgetkey",
    "ton_fnc_cell_deprequest",
    "ton_fnc_clientgangleader",
    "ton_fnc_cell_textcop",
    "ton_fnc_clientwiretransfer",
    "ton_fnc_cell_textmsg",
    "ton_fnc_cell_adminmsg",
    "ton_fnc_clientgangkick",
    "ton_fnc_clientmessage",
    "ton_fnc_cell_emsrequest",
    "ton_fnc_cell_adminmsgall",
    "ton_fnc_player_query",
    "ton_fnc_cell_textadmin",
    "ton_fnc_cleanup",
    "ton_fnc_huntingzone",
    "ton_fnc_getid" ,
    "ton_fnc_vehiclecreate",
    "ton_fnc_vehicledead",
    "ton_fnc_spawnvehicle",
    "ton_fnc_getvehicles", 
    "ton_fnc_vehiclestore", 
    "ton_fnc_vehicledelete", 
    "ton_fnc_spikestrip", 
    "ton_fnc_logit", 
    "ton_fnc_federalupdate", 
    "ton_fnc_chopshopsell", 
    "ton_fnc_clientdisconnect", 
    "ton_fnc_cleanuprequest",
    "ton_fnc_setobjvar",
    "ton_fnc_keymanagement",
    "ton_fnc_insurecar",
    "ton_fnc_addhouse",
    "ton_fnc_fetchplayerhouses",
    "ton_fnc_inithouses",
    "ton_fnc_sellhouse",
    "ton_fnc_updatehousecontainers",
    "ton_fnc_updatehousetrunk",
    "ton_fnc_housecleanup",
    "ton_fnc_insertgang",
    "ton_fnc_queryplayergang",
    "ton_fnc_removegang"
    };
  };
};